on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            # `yarn` returned some registry errors so I opted for `npm`
            - name: Install
              run: npm i

            # Step 3 starts here !!!
            - name: Build
              run: npm run build

            - name: Export
              run: npm run export

            # Step 4 starts here !!!
            - name: Deploy
              run: npm run cdk deploy --require-approval=never
